#!/usr/bin/env bash
#1den 100e kimi 3 5 bolenleri

for i in {1..100}; do
    if [ $(( i % 3 )) -eq 0 ] && [ $(( i % 5 )) -ne 0 ]; then
        echo "Fizz"
    elif [ $(( i % 5 )) -eq 0 ] && [ $(( i % 3 )) -ne 0 ]; then
        echo "Buzz"
    elif [ $(( i % 3 )) -eq 0 ] && [ $(( i % 5 )) -eq 0 ]; then
        echo "FizzBuzz"
    else
        echo "$i"
    fi
done
 
