#!/usr/bin/env bash
# This script reads the apache-access.log file, groups visitors by IP and HTTP status code,
# and displays the total occurrences, sorted from highest to lowest.
awk '
{
    KEY = $1 " " $9
    counts[KEY]++
}
END {
    for (key in counts) {
        print counts[key], key
    }
}
' apache-access.log | sort -rn
