#!/usr/bin/env bash
# This script reads the apache-access.log file, groups visitors by IP and HTTP status code,
# and displays the total occurrences, sorted from highest to lowest.

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr

