#!/usr/bin/env bash
# #*- sintaksisi variable da - a qeder olan herseyi silir
for file in *; do
    [ -e "$file" ] || continue

    case "$file" in
        -*)
            echo "${file#*-}"
            ;;
        *-*)
            echo "${file#*-}"
            ;;
        *)
            echo "$file"
            ;;
    esac
done
