#!/usr/bin/env bash
# Bu skript PID faylını idarə edir və siqnalları tutur.

PID_FILE="/var/run/myscript.pid"

if [ "$(whoami)" != "root" ]; then
    echo "XƏTA: Bu skript /var/run qovluğuna yazmaq üçün root (sudo) icazələri tələb edir." 1>&2
    echo "Zəhmət olmasa: sudo ./10-process_and_pid_file kimi işə salın." 1>&2
fi

cleanup_and_exit() {
    
    rm -f "$PID_FILE"
    exit 0
}

sigterm_handler() {
    echo "I hate the kill command"
    cleanup_and_exit
}

sigint_handler() {
    echo "Y U no love me?!"
}

echo "$$" > "$PID_FILE" || exit 1
ı
trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'cleanup_and_exit' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
