#!/usr/bin/env bash
# Bu skript PID faylını idarə edir və siqnalları tutur.

PID_FILE="/var/run/myscript.pid"

cleanup_and_exit() {
    sudo rm -f "$PID_FILE"
    exit 0
}

sigterm_handler() {
    echo "I hate the kill command"
    cleanup_and_exit
}

sigint_handler() {
    echo "Y U no love me?!"
}

echo "$$" | sudo tee "$PID_FILE" > /dev/null || exit 1

trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'cleanup_and_exit' SIGQUIT


while true; do
    echo "To infinity and beyond"
    sleep 2
done
